CREATE TABLE Author (
	ID CHAR(10) NOT NULL,
	Name CHAR(250) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE Book (
	ISBN CHAR(15) NOT NULL,
	Title CHAR(250) NOT NULL,
	Edition CHAR(10) NOT NULL,
	YearIssued INT NOT NULL,
	PRIMARY KEY(ISBN)
);

CREATE TABLE Copy (
	barCode CHAR(10) NOT NULL,
	Book_ID CHAR(15) NOT NULL,
	PRIMARY KEY(barCode),
	FOREIGN KEY(Book_ID) REFERENCES Book(ISBN)
);

CREATE TABLE Authorship (
	ID INT AUTO_INCREMENT NOT NULL,
	Book_ID CHAR(15) NOT NULL,
	Author_ID CHAR(10) NOT NULL,
	Main BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(Book_ID) REFERENCES Book(ISBN),
	FOREIGN KEY(Author_ID) REFERENCES Author(ID)
);

CREATE TABLE Member (
	ID INT AUTO_INCREMENT NOT NULL,
	Name CHAR(250) NOT NULL,
	GENDER INT NOT NULL,
	email CHAR(250) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE Loan (
	ID INT AUTO_INCREMENT NOT NULL,
	copyID CHAR(10) NOT NULL,
	memberID INT NOT NULL,
	borrowDate DATE NOT NULL,
	returnDate DATE NULL,
	status INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(copyID) REFERENCES Copy(barCode),
	FOREIGN KEY(memberID) REFERENCES Member(ID)
);